Issues/1
yeongwooCho/CloneApp_Calculator pull request #2
Opened 2022-05-30 07:24 UTC by yeongwooCho

### 처리한 이슈: #1 

1. Main interface가 Main Storyboard로 되어 있는 것을 제거
2. Info.plish에서 Main Storyboard 지정 되어 있는 것을 제거
3. Main Storybard 파일 제거
4. UI Component(button)로 code ui test
5. Constraints로 UI Component Frame 제어

2022-05-30 11:26 UTC, Lia316 requested changes
코드로 UI 작성하는 기본 세팅하느라 수고하셨습니다! 😆

어디까지나 리뷰어의 의견이니, 제가 드린 코멘트를 모두 따를 필요도 없습니다.
저도 배우는 입장이라 리뷰가 미숙할 수도 있고, 제대로 이해하지 못한 게 있을 수도 있습니다..!
코멘트로 이야기해보면서 같이 배워나가면 좋을 것 같아요!

2022-05-30 11:26 UTC, Lia316 commented on CloneApp_Calculator/SceneDelegate.swift
> +//        guard let _ = (scene as? UIWindowScene) else { return }
기본 주석은 과감하게 삭제해도 좋습니다.
또한, 더 이상 사용하지 않는 코드도 주석으로 두기 보다는 삭제하는 게 좋습니다.

'내 코드에 주석이 꼭 필요한가?' 생각해봤을 때, 
기본 코드나 사용하지 않는 코드는 큰 의미를 갖지 않기 때문에 삭제해도 좋을 것 같다고 생각했습니다!

2022-05-30 11:26 UTC, Lia316 commented on CloneApp_Calculator/SceneDelegate.swift
>      func sceneDidDisconnect(_ scene: UIScene) {
여기서부터 아래 코드를 리뷰 범위로 설정하고 싶은데 안 되네요 💦

마찬가지로, 기본 주석은 삭제하는 게 좋습니다.
또한, 지금 사용하고 있지 않는 코드도 삭제하는 게 좋습니다.

2022-05-30 11:26 UTC, Lia316 commented on CloneApp_Calculator/ViewController.swift
>  class ViewController: UIViewController {
기본 뷰컨트롤러 이름보다는, 
무엇을 위한 뷰컨트롤러인지 변수명을 구체적으로 명명해주시면 SceneDelegate.swift 파일에서도 흐름 이해가 더 쉬울 것 같습니다!

2022-05-30 11:26 UTC, Lia316 commented on CloneApp_Calculator/ViewController.swift
> +    @objc func defaultButtonTapHandler(sender: UIButton) {
줄 간격 조정 부탁드립니다 :)

2022-05-30 11:26 UTC, Lia316 commented on CloneApp_Calculator/ViewController.swift
> +    }
이 부분은 모두 뷰를 세팅하는 부분인데 함수를 나누신 이유가 궁금합니다!
앞으로 추가할 뷰가 늘어나면, 서브 뷰를 따로 관리하기 위해서 두신 게 맞을까요?

현재로선 둘 다 코드 양이 적어서 합쳐도 될 것 같다고 생각했는데,
위에 말씀 드린 이유가 맞다면 분리하는 게 확실히 좋을 것 같네요!

2022-05-30 11:26 UTC, Lia316 commented on CloneApp_Calculator/ViewController.swift
> +    lazy var defaultButton: UIButton = {
defaultButton의 역할은 무엇인가요?
변수명만으로는 어떤 기본 버튼인지 쉽게 이해할 수 없어서 질문 드립니다

2022-05-30 11:48 UTC, yeongwooCho commented on CloneApp_Calculator/SceneDelegate.swift
> +//        guard let _ = (scene as? UIWindowScene) else { return }
기본 코드 및 주석은 계속 가져가는 것으로 계획했는데, 
"기본 코드나 사용하지 않는 코드는 큰 의미를 갖지 않기 때문에 삭제해도 좋을 것 같다"는 되게 좋은 말씀 이네요!!
정리하겠습니다!!

2022-05-30 11:48 UTC, yeongwooCho commented on CloneApp_Calculator/SceneDelegate.swift
>      func sceneDidDisconnect(_ scene: UIScene) {
위와 같은 내용이네요! 감사합니다!

2022-05-30 11:51 UTC, yeongwooCho commented on CloneApp_Calculator/SceneDelegate.swift
>      }
칭찬 감사해요!! 뿌리는 해석을 하다가 적었는데, 자주 쓰이는 표현은 아닌거 같아요😁

2022-05-30 11:52 UTC, yeongwooCho commented on CloneApp_Calculator/ViewController.swift
>  class ViewController: UIViewController {
고민을 하다가 "귀찮으니깐 넘어가자"라는 아주 안 좋은 습관이 나온 것 같네요!! 수정하겠습니다!

2022-05-30 11:54 UTC, yeongwooCho commented on CloneApp_Calculator/ViewController.swift
> +    @objc func defaultButtonTapHandler(sender: UIButton) {
바로 위 버튼에 해당하는 action이라서 평소 붙혀서 사용했었는데, 약속되지 않은 부분이니 줄 간격 수정하겠습니다!!

2022-05-30 11:56 UTC, yeongwooCho commented on CloneApp_Calculator/ViewController.swift
> +    }
네! 사용하는 UIComponents 갯수가 10개가 넘어가다 보니, 뷰 셋팅과 서브 뷰를 관리하는 기능을 각각 다른 함수로 분리했습니다.

2022-05-30 12:00 UTC, yeongwooCho commented on CloneApp_Calculator/ViewController.swift
> +    lazy var defaultButton: UIButton = {
defaultButton은 UIKit에서 컴포넌트를 셋팅하는 과정을 구현하기 위한 테스트 작업이었습니다.
merge할 코드로 적합하지 않음을 인지했습니다. 제외 시키겠습니다.

2022-05-30 12:23 UTC, Lia316 commented
@yeongwooCho  혹시 수정 사항은 다음 PR 때 반영하실 건가요?
그럴 계획이시면 지금 approve 하려고 하고, 아니면 수정 사항까지 보고 approve 하려고 합니다!

2022-05-30 12:43 UTC, yeongwooCho commented
> @yeongwooCho 혹시 수정 사항은 다음 PR 때 반영하실 건가요?
> 그럴 계획이시면 지금 approve 하려고 하고, 아니면 수정 사항까지 보고 approve 하려고 합니다!

@Lia316 
어디서 답글 적는지 찾는다고 답변이 늦었네요. 수정 사항 반영 완료했습니다!!

2022-05-30 13:11 UTC, Lia316 approved these changes

2022-05-30 13:28 UTC, merged

2022-05-31 06:54 UTC, Lia316 commented
[ba92ca9](https://github.com/DeveloperAcademy-POSTECH/CCC-1st-Calculator-Bit/pull/2/commits/ba92ca9513993804d57ac7a60a3802ae682a2399)